-- Q1. What is total revenue generated by male vs female customers?
select gender,sum(Purchase_Amount_USD) as revenue from cutomer_shopping 
where (gender = 'male') or (gender = 'female') group by gender;

-- Q2. Which customers used discount but still spend more than the average purchase amount?
select customer_id ,Purchase_Amount_USD from cutomer_shopping
 where Discount_Applied = 'yes' and Purchase_Amount_USD >= ( select  avg(Purchase_Amount_USD) 
 from cutomer_shopping);

-- Q3. Which are the top 5 products with highest average review rating?
select Item_Purchased,
round(avg(Review_Rating),2) as "Average product rating" from cutomer_shopping
 group by Item_Purchased order by "average product rating" desc limit 5;
 
-- Q4. Compare the average purchase amounts between standard and express shipping?
select shipping_type ,round(avg(purchase_amount_usd),3) 
from cutomer_shopping where Shipping_Type in ('standard','express') group  by Shipping_Type;

-- Q5. Do subscribedcustomers spend more ? compare average spend and total revenue
-- between subscribers and non subscribers?

select subscription_status,
count(customer_id) as total_customers ,
round(avg(purchase_amount_usd),2) as avg_spending ,
round(sum(purchase_amount_usd),2) as total_revenue from cutomer_shopping 
group by Subscription_Status order by total_revenue ,avg_spending desc; 

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select  item_purchased ,
round(100 * sum(CASE WHEN discount_applied = 'yes' then 1 else 0 END)/count(*),2) as discount_rate
from cutomer_shopping 
group by Item_Purchased 
order by discount_rate desc limit 5;

-- Q7. segemnt customers into new,returning and loyal based on their total number of previous
-- purchases and show the count of each segment?

with customer_type as (
select customer_id,previous_purchases,
case 
	when Previous_Purchases = 1 then 'New' 
	when previous_purchases between 2 and 10 then 'Returing' 
	else 'loyal' 
    end  as customer_segment
    from cutomer_shopping
)
select customer_segment ,count(*) as 'number of customers'
from customer_type
group by customer_segment;

-- Q8. What are top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased ,
count(Customer_ID) as total_orders,
row_number() over(partition by category order by count(Customer_ID) desc ) as item_rank  
from cutomer_shopping
 group by Category,Item_Purchased   
)
select item_rank ,category ,item_purchased ,total_orders from item_counts where item_rank <= 3 ;

-- Q9.Are customers repeat buyers(more than 5 previous purchases) are likely to subscribe?
select Subscription_Status,count(Customer_ID)  as repeat_buyers from cutomer_shopping
where Previous_Purchases > 5 group by Subscription_Status;

-- Q10. what is the reveue contribution of each age group?
 select sum(purchase_amount_usd) as revenue ,age from cutomer_shopping 
 group by age order by revenue desc  ;
 


